# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AvaFrameConnector
                                 A QGIS plugin
 Connects to AvaFrame
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-26
        copyright            : (C) 2021 by AvaFrame Team
        email                : felix@avaframe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'AvaFrame Team'
__date__ = '2021-08-26'
__copyright__ = '(C) 2021 by AvaFrame Team'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AvaFrameConnector class from file AvaFrameConnector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .avaframeConnector import AvaFrameConnectorPlugin
    return AvaFrameConnectorPlugin()
